services:
    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: bar
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
